server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - name: CircuitBreaker
              args:
                name: userService
                fallbackUri: forward:/fallback/user-service
            - RewritePath=/api/users/(?<segment>.*), /$\{segment}

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notifications/**
          filters:
            - name: CircuitBreaker
              args:
                name: notificationService
                fallbackUri: forward:/fallback/notification-service
            - RewritePath=/api/notifications/(?<segment>.*), /$\{segment}

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/