spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC

logging:
  level:
    root: INFO
    com.example: DEBUG
    org.springframework.cloud: INFO
    org.springframework.web: INFO

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true

resilience4j:
  circuitbreaker:
    instances:
      default:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 30s
        failure-rate-threshold: 50
        permitted-number-of-calls-in-half-open-state: 3